// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Smart_Toury.Identity.Infrastructure;

#nullable disable

namespace Smart_Toury.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260504105225_Identity.ClearRefreshToken")]
    partial class IdentityClearRefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Smart_Toury.Identity.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "identity");
                });

            modelBuilder.Entity("Smart_Toury.Identity.Domain.Users.GuideProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GuestsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer");

                    b.Property<string>("ShortLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("ToursCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GuideProfiles", "identity");
                });

            modelBuilder.Entity("Smart_Toury.Identity.Domain.Users.TouristProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AchievementsCount")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedTours")
                        .HasColumnType("integer");

                    b.Property<int>("FavoritesCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReviewsLeft")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TouristProfiles", "identity");
                });

            modelBuilder.Entity("Smart_Toury.Identity.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("Smart_Toury.Identity.Domain.RefreshToken", b =>
                {
                    b.HasOne("Smart_Toury.Identity.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Smart_Toury.Identity.Domain.Users.GuideProfile", b =>
                {
                    b.HasOne("Smart_Toury.Identity.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Smart_Toury.Identity.Domain.Users.GuideProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Smart_Toury.Identity.Domain.Users.TouristProfile", b =>
                {
                    b.HasOne("Smart_Toury.Identity.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Smart_Toury.Identity.Domain.Users.TouristProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Smart_Toury.Identity.Domain.Users.TouristPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("TouristProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AccessibilityMode")
                                .HasColumnType("integer");

                            b1.Property<bool>("ReceiveDiscountNotifications")
                                .HasColumnType("boolean");

                            b1.Property<int>("RouteAtmosphere")
                                .HasColumnType("integer");

                            b1.HasKey("TouristProfileId");

                            b1.ToTable("TouristProfiles", "identity");

                            b1.WithOwner()
                                .HasForeignKey("TouristProfileId");
                        });

                    b.OwnsOne("Smart_Toury.Identity.Domain.Users.TouristTravelStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("TouristProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ActivityLevelPercentage")
                                .HasColumnType("integer");

                            b1.Property<int>("CitiesVisited")
                                .HasColumnType("integer");

                            b1.Property<int>("CountriesVisited")
                                .HasColumnType("integer");

                            b1.Property<double>("DistanceCoveredKm")
                                .HasColumnType("double precision");

                            b1.Property<int>("HoursInTours")
                                .HasColumnType("integer");

                            b1.Property<double>("Rating")
                                .HasColumnType("double precision");

                            b1.HasKey("TouristProfileId");

                            b1.ToTable("TouristProfiles", "identity");

                            b1.WithOwner()
                                .HasForeignKey("TouristProfileId");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("Stats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
